"use client"

import { ChevronRight, Loader2, Check } from "lucide-react"
import type { ChatMessageRecord, ChatStreamStageName } from "@/lib/api"
import type { StreamingAssistant, StreamingStage } from "@/hooks/useChatManagement"
import { formatListTimestamp } from "@/lib/utils"
import { Markdown } from "@/components/markdown"

interface ChatMessagesProps {
  activeChatMessages: ChatMessageRecord[]
  isLoadingActiveChat: boolean
  streamingAssistant: StreamingAssistant | null
}

const STAGE_LABELS: Record<ChatStreamStageName, (count?: number) => string> = {
  queued: () => "Waiting for the model",
  searching: () => "Searching your sources",
  retrieved: (count) => `Read ${count ?? 0} relevant chunk${count === 1 ? "" : "s"}`,
  thinking: () => "Thinking",
  writing: () => "Writing answer",
}

function StageRow({ stage, thinking }: { stage: StreamingStage; thinking?: string }) {
  const label = STAGE_LABELS[stage.name](stage.count)
  const icon = stage.done ? (
    <Check className="h-3.5 w-3.5 text-emerald-600" />
  ) : (
    <Loader2 className="h-3.5 w-3.5 animate-spin text-muted-foreground" />
  )

  if (stage.name === "thinking" && thinking) {
    return (
      <details className="group" open={!stage.done}>
        <summary className="flex items-center gap-2 cursor-pointer list-none text-xs text-muted-foreground hover:text-foreground">
          {icon}
          <ChevronRight className="h-3 w-3 transition-transform group-open:rotate-90" />
          <span>{label}</span>
        </summary>
        <div className="mt-1.5 ml-7 text-xs text-muted-foreground whitespace-pre-wrap border-l-2 border-muted-foreground/20 pl-2">
          {thinking}
        </div>
      </details>
    )
  }

  return (
    <div className="flex items-center gap-2 text-xs text-muted-foreground">
      {icon}
      <span>{label}</span>
    </div>
  )
}

export function ChatMessages({ activeChatMessages, isLoadingActiveChat, streamingAssistant }: ChatMessagesProps) {
  return (
    <div className="flex-1 min-h-0 overflow-y-auto no-scrollbar p-6">
      <div className="max-w-2xl mx-auto space-y-4">
        {isLoadingActiveChat ? (
          <p className="text-sm text-muted-foreground text-center">Loading chat...</p>
        ) : (
          activeChatMessages.map((message) => {
            const timestamp = formatListTimestamp(message.created_at)
            if (message.role === "question") {
              const hasThinking = !!(message.thinking && message.thinking.trim())
              return (
                <div key={message.id} className="flex justify-start">
                  <div className="bg-muted rounded-2xl rounded-tl-sm px-4 py-3 max-w-[85%]">
                    {hasThinking && (
                      <details className="group mb-2">
                        <summary className="flex items-center gap-1 cursor-pointer list-none text-xs text-muted-foreground hover:text-foreground">
                          <ChevronRight className="h-3 w-3 transition-transform group-open:rotate-90" />
                          <span>Thoughts</span>
                        </summary>
                        <div className="mt-1.5 text-xs text-muted-foreground whitespace-pre-wrap border-l-2 border-muted-foreground/20 pl-2">
                          {message.thinking}
                        </div>
                      </details>
                    )}
                    <Markdown className="text-[15px]">{message.text}</Markdown>
                    <div className="flex items-center justify-between gap-2 mt-1.5">
                      <span className="text-[10px] text-muted-foreground">{timestamp}</span>
                      {message.model && (
                        <span className="text-[10px] text-muted-foreground/70 font-mono">
                          generated by: {message.model}
                        </span>
                      )}
                    </div>
                  </div>
                </div>
              )
            }
            const answerText =
              message.scale_value !== null && message.scale_value !== undefined
                ? `${message.scale_value}/${message.scale_max ?? 10}`
                : message.text
            return (
              <div key={message.id} className="flex justify-end">
                <div className="bg-emerald-900 text-white rounded-2xl rounded-tr-sm px-4 py-3 max-w-[85%]">
                  <p className="text-[15px] whitespace-pre-wrap">{answerText}</p>
                  <div className="flex items-center justify-end gap-2 mt-1.5">
                    <span className="text-[10px] text-white/70">{timestamp}</span>
                  </div>
                </div>
              </div>
            )
          })
        )}

        {streamingAssistant && (
          <div className="flex justify-start">
            <div className="bg-muted rounded-2xl rounded-tl-sm px-4 py-3 max-w-[85%] min-w-[200px]">
              {streamingAssistant.stages.length > 0 && (
                <details className="group mb-2" open>
                  <summary className="flex items-center gap-1 cursor-pointer list-none text-xs text-muted-foreground hover:text-foreground">
                    <ChevronRight className="h-3 w-3 transition-transform group-open:rotate-90" />
                    <span>Process</span>
                  </summary>
                  <div className="mt-1.5 space-y-1.5 pl-1">
                    {streamingAssistant.stages.map((stage, i) => (
                      <StageRow
                        key={`${stage.name}-${i}`}
                        stage={stage}
                        thinking={stage.name === "thinking" ? streamingAssistant.thinking : undefined}
                      />
                    ))}
                  </div>
                </details>
              )}
              {streamingAssistant.answer ? (
                <Markdown className="text-[15px]">{streamingAssistant.answer}</Markdown>
              ) : streamingAssistant.stages.length === 0 ? (
                <div className="flex items-center gap-1">
                  <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground/60 animate-bounce [animation-delay:-0.3s]" />
                  <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground/60 animate-bounce [animation-delay:-0.15s]" />
                  <span className="h-1.5 w-1.5 rounded-full bg-muted-foreground/60 animate-bounce" />
                </div>
              ) : null}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
