"""changed created at for journal entry

Revision ID: 2422bed80cc9
Revises: 16b8c20524e6
Create Date: 2026-03-18 10:16:27.983958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2422bed80cc9'
down_revision: Union[str, Sequence[str], None] = '16b8c20524e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journalentry', sa.Column('test', sa.String(), nullable=True))
    op.add_column('journalentry', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('journalentry', sa.Column('edited_at', sa.DateTime(), nullable=False))
    op.alter_column('qaentry', 'timestamp',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qaentry', 'timestamp',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('journalentry', 'edited_at')
    op.drop_column('journalentry', 'created_at')
    op.drop_column('journalentry', 'test')
    # ### end Alembic commands ###
