"""added transcript_segments to source

Revision ID: 34a06fa3ac33
Revises: 1f71e699b478
Create Date: 2026-05-08 08:52:10.234973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34a06fa3ac33'
down_revision: Union[str, Sequence[str], None] = '1f71e699b478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scale_question', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('source', sa.Column('transcript_segments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'transcript_segments')
    op.alter_column('scale_question', 'source_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
