"""testing alembic with test field in journalentry table

Revision ID: 39783686c193
Revises: 47ff3ce9ad69
Create Date: 2026-03-17 23:02:14.571093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39783686c193'
down_revision: Union[str, Sequence[str], None] = '47ff3ce9ad69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journalentry', sa.Column('test', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journalentry', 'test')
    # ### end Alembic commands ###
