"""added filepath to journal

Revision ID: 7bb8a711c1a6
Revises: b9770477adc9
Create Date: 2026-03-23 15:19:33.687182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bb8a711c1a6'
down_revision: Union[str, Sequence[str], None] = 'b9770477adc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('file_path', sa.String(length=255), nullable=True))
    op.drop_column('journal', 'file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('file_id', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('journal', 'file_path')
    # ### end Alembic commands ###
