"""updated journal for saving origional file

Revision ID: b9770477adc9
Revises: e36510b9f747
Create Date: 2026-03-23 14:43:01.473676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9770477adc9'
down_revision: Union[str, Sequence[str], None] = 'e36510b9f747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('file_id', sa.String(length=255), nullable=True))
    op.add_column('journal', sa.Column('filename', sa.String(length=255), nullable=True))
    op.add_column('journal', sa.Column('file_type', sa.String(length=255), nullable=True))
    op.drop_column('journal', 'source_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('source_type', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('journal', 'file_type')
    op.drop_column('journal', 'filename')
    op.drop_column('journal', 'file_id')
    # ### end Alembic commands ###
